[bar.default]
center = []
end = [
    "sysmon",
    "tray",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "battery",
    "control-center",
    "notifications",
    "session",
    "clock"
]
margin_edge = 0
margin_ends = 0
radius = 0
shadow = false
start = [ "workspaces", "active_window" ]
thickness = 25

[calendar]
enabled = true

[desktop_widgets]
enabled = false

[idle]
behavior_order = [ "idle-behavior", "idle-behavior-2" ]
pre_action_fade_seconds = 15

    [idle.behavior.idle-behavior]
    action = "screen_off"
    enabled = true
    timeout = 600

    [idle.behavior.idle-behavior-2]
    action = "lock"
    enabled = true
    timeout = 900

[location]
address = "Beau Bassin-Rose Hill"
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 640.0
    cy = 597.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[nightlight]
enabled = true

[shell]
avatar_path = "/home/felix/.face"
polkit_agent = true
settings_show_advanced = true

[theme]
builtin = "Tokyo-Night"
custom_palette = "Base16"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

[wallpaper]
directory = "/home/felix/downloads"
transition = [ "honeycomb" ]
transition_on_startup = true

    [wallpaper.default]
    path = "~/.cache/frottage/current-wallpaper.jpg"

    [wallpaper.last]
    path = "~/.cache/frottage/current-wallpaper.jpg"

    [wallpaper.monitors.eDP-1]
    path = "~/.cache/frottage/current-wallpaper.jpg"

    [[wallpaper.favorite]]
    custom_palette = "Base16"
    palette_source = "custom"
    path = "/home/felix/downloads/felixdietze_trippy_Bear_with_big_eyes_hypnotizing_you_--ar_199__68a7a350-c34f-4523-9d89-53a4188f955d.png"
    theme_mode = "auto"

[widget.battery]
display_mode = "graphic"
hide_when_full = true

[widget.network]
show_label = false

[widget.sysmon]
display = "graph"
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
display = "name"
empty_color = "on_primary"
occupied_color = "tertiary"