[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

[templates.alacritty]
input_path  = "/home/felix/projects/dotfiles/home/noctalia/templates/alacritty.toml"
output_path = "/home/felix/.config/noctalia/generated/alacritty-colors.toml"
post_hook   = ""

