-- AUTOGENERATED at runtime by noctalia from home/noctalia/templates/wezterm-colors.lua.
-- Edits are overwritten on the next theme change.
--
-- Maps terminal_* tokens to WezTerm's inline colors table. Loaded at runtime via pcall(dofile, ...) in
-- the wezterm config — no color_scheme name needed.
return {
  colors = {
    foreground    = '{{colors.terminal_foreground.default.hex}}',
    background    = '{{colors.terminal_background.default.hex}}',
    cursor_bg     = '{{colors.terminal_cursor.default.hex}}',
    cursor_border = '{{colors.terminal_cursor.default.hex}}',
    cursor_fg     = '{{colors.terminal_cursor_text.default.hex}}',
    selection_bg  = '{{colors.terminal_selection_bg.default.hex}}',
    selection_fg  = '{{colors.terminal_selection_fg.default.hex}}',
    ansi = {
      '{{colors.terminal_normal_black.default.hex}}',
      '{{colors.terminal_normal_red.default.hex}}',
      '{{colors.terminal_normal_green.default.hex}}',
      '{{colors.terminal_normal_yellow.default.hex}}',
      '{{colors.terminal_normal_blue.default.hex}}',
      '{{colors.terminal_normal_magenta.default.hex}}',
      '{{colors.terminal_normal_cyan.default.hex}}',
      '{{colors.terminal_normal_white.default.hex}}',
    },
    brights = {
      '{{colors.terminal_bright_black.default.hex}}',
      '{{colors.terminal_bright_red.default.hex}}',
      '{{colors.terminal_bright_green.default.hex}}',
      '{{colors.terminal_bright_yellow.default.hex}}',
      '{{colors.terminal_bright_blue.default.hex}}',
      '{{colors.terminal_bright_magenta.default.hex}}',
      '{{colors.terminal_bright_cyan.default.hex}}',
      '{{colors.terminal_bright_white.default.hex}}',
    },
    -- pi-terminal-theme "terminal-tinted" custom palette slots 16..23 (full
    -- slot->token rationale in kitty-colors.conf). Status backgrounds 17/18/19/21
    -- are MD3 *_container tokens darkened+desaturated into readable tints; 22 uses
    -- on_surface so the tool title stays readable on every tint in both modes. All
    -- tokens are derived per active light/dark mode, replacing the xterm cube.
    indexed = {
      [16] = '{{colors.surface_container_high.default.hex}}',
      [17] = '{{colors.error_container.default.hex | darken 20 | desaturate 25}}',
      [18] = '{{colors.primary_container.default.hex | darken 20 | desaturate 25}}',
      [19] = '{{colors.tertiary_container.default.hex | darken 20 | desaturate 25}}',
      [20] = '{{colors.surface_container.default.hex}}',
      [21] = '{{colors.secondary_container.default.hex | darken 20 | desaturate 25}}',
      [22] = '{{colors.on_surface.default.hex}}',
      [23] = '{{colors.on_surface_variant.default.hex}}',
    },
  }
}
