-- AUTOGENERATED at runtime by noctalia from home/noctalia/templates/wezterm-colors.lua.
-- Edits are overwritten on the next theme change.
--
-- Maps terminal_* tokens to WezTerm's inline colors table. Loaded at runtime via pcall(dofile, ...) in
-- the wezterm config — no color_scheme name needed.
return {
  colors = {
    foreground    = '{{colors.terminal_foreground.default.hex}}',
    background    = '{{colors.terminal_background.default.hex}}',
    cursor_bg     = '{{colors.terminal_cursor.default.hex}}',
    cursor_border = '{{colors.terminal_cursor.default.hex}}',
    cursor_fg     = '{{colors.terminal_cursor_text.default.hex}}',
    selection_bg  = '{{colors.terminal_selection_bg.default.hex}}',
    selection_fg  = '{{colors.terminal_selection_fg.default.hex}}',
    ansi = {
      '{{colors.terminal_normal_black.default.hex}}',
      '{{colors.terminal_normal_red.default.hex}}',
      '{{colors.terminal_normal_green.default.hex}}',
      '{{colors.terminal_normal_yellow.default.hex}}',
      '{{colors.terminal_normal_blue.default.hex}}',
      '{{colors.terminal_normal_magenta.default.hex}}',
      '{{colors.terminal_normal_cyan.default.hex}}',
      '{{colors.terminal_normal_white.default.hex}}',
    },
    brights = {
      '{{colors.terminal_bright_black.default.hex}}',
      '{{colors.terminal_bright_red.default.hex}}',
      '{{colors.terminal_bright_green.default.hex}}',
      '{{colors.terminal_bright_yellow.default.hex}}',
      '{{colors.terminal_bright_blue.default.hex}}',
      '{{colors.terminal_bright_magenta.default.hex}}',
      '{{colors.terminal_bright_cyan.default.hex}}',
      '{{colors.terminal_bright_white.default.hex}}',
    },
    -- pi-terminal-theme "terminal-tinted" custom palette slots 16..23 (full
    -- slot->token rationale in kitty-colors.conf). Status backgrounds 17/18/19/21
    -- are surface_container_high stamped with a fixed semantic hue (set_saturation 30
    -- | set_hue H): the MD3 *_container tokens vary too much in lightness across
    -- schemes (vivid for base16, near-black for wallpaper), so they're replaced by a
    -- dim mode-correct surface + fixed hue. 22 uses on_surface so the title reads.
    indexed = {
      [16] = '{{colors.surface_container_high.default.hex}}',
      [17] = '{{colors.surface_container_high.default.hex | set_saturation 30 | set_hue 2}}',
      [18] = '{{colors.surface_container_high.default.hex | set_saturation 30 | set_hue 135}}',
      [19] = '{{colors.surface_container_high.default.hex | set_saturation 30 | set_hue 222}}',
      [20] = '{{colors.surface_container.default.hex}}',
      [21] = '{{colors.surface_container_high.default.hex | set_saturation 30 | set_hue 300}}',
      [22] = '{{colors.on_surface.default.hex}}',
      [23] = '{{colors.on_surface_variant.default.hex}}',
    },
  }
}
