#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload


# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1    # Use left alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-y reload
hc keybind $Mod-q close
hc keybind $Mod-x close
hc keybind $Mod-k spawn xkill
hc keybind $Mod-d spawn termitexcwd
hc keybind $Mod-y spawn xboomx
hc keybind $Mod-Shift-d spawn nmcli_dmenu
hc keybind $Mod-Shift-p spawn xrandr --output eDP1  --auto --primary --output VGA1 --off --output HDMI1 --off
hc keybind $Mod-Shift-z spawn movietime
hc keybind Print spawn scrot

# adjust volume
hc keybind $Mod-Ctrl-h chain , spawn pulseaudio-ctl up   , emit_hook panel_refresh
hc keybind $Mod-Ctrl-n chain , spawn pulseaudio-ctl down , emit_hook panel_refresh
hc keybind $Mod-Ctrl-m chain , spawn pulseaudio-ctl mute , emit_hook panel_refresh

# adjust screen brightness
hc keybind $Mod-Ctrl-g spawn xbacklight +5 -steps 1 -time 0
hc keybind $Mod-Ctrl-r spawn xbacklight -5 -steps 1 -time 0

# adjust keyboard backlight brightness
hc keybind $Mod-Ctrl-f spawn sudo asus-kbd-backlight up
hc keybind $Mod-Ctrl-t spawn sudo asus-kbd-backlight down

# lock screen
hc keybind $Mod-u spawn lock

# control media players with yxcvb (üöäpz on NEO)
hc keybind $Mod-udiaeresis spawn playerctl previous
hc keybind $Mod-odiaeresis spawn playerctl play
hc keybind $Mod-adiaeresis spawn playerctl play-pause
hc keybind $Mod-p          spawn playerctl stop
hc keybind $Mod-z          spawn playerctl next

# enable and disable wifi
hc keybind $Mod-Ctrl-q spawn nmcli radio wifi on
hc keybind $Mod-Ctrl-d spawn nmcli radio wifi off

# set default layout to grid
hc set default_frame_layout 3
herbstclient set_layout grid

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-i     focus left
hc keybind $Mod-a     focus down
hc keybind $Mod-l     focus up
hc keybind $Mod-e     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-i     shift left
hc keybind $Mod-Shift-a     shift down
hc keybind $Mod-Shift-l     shift up
hc keybind $Mod-Shift-e     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-g       chain , split   top    0.62 , focus up
hc keybind $Mod-r       chain , split   bottom 0.62 , focus down
hc keybind $Mod-n       chain , split   left   0.62 , focus left
hc keybind $Mod-t       chain , split   right  0.62 , focus right
# let the current frame explode into subframes
hc keybind $Mod-m split explode

# resizing frames
resizestep=0.02
hc keybind $Mod-Shift-g         resize up +$resizestep
hc keybind $Mod-Shift-r         resize down +$resizestep
hc keybind $Mod-Shift-n         resize left +$resizestep
hc keybind $Mod-Shift-t         resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-F$key" use_index "$i"
        hc keybind "$Mod-Shift-F$key" chain , move_index "$i" , use_index $i
    fi
done

# cycle through tags
hc keybind $Mod-c use_index +1 --skip-visible
hc keybind $Mod-Shift-c chain ,  move_index  +1 --skip-visible , use_index +1
hc keybind $Mod-v use_index -1 --skip-visible
hc keybind $Mod-Shift-v chain ,  move_index  -1 --skip-visible , use_index -1

hc keybind $Mod-w use_previous

# layouting
hc keybind $Mod-comma remove
hc keybind $Mod-Shift-h cycle_layout 1
hc keybind $Mod-h floating toggle
hc keybind $Mod-f fullscreen toggle
#hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
#hc keybind $Mod-c cycle
hc keybind $Mod-b jumpto urgent



hc set always_show_frame 1
hc set frame_border_inner_width 0
hc set window_border_inner_width 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_border_inner_width 0
hc set frame_gap 0
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1

# hc set frame_border_width 2
# hc set frame_border_normal_color '#343434'
# hc set frame_border_active_color '#37BAFF'

# hc set window_border_width 2
# hc set window_border_normal_color '#343434'
# hc set window_border_active_color '#37BAFF'

# set dark terminal and vim colors if not set
if [ ! -f ~/.colors ]; then
    # black background
    xsetroot -solid '#000000'

    if daytime; then
        light nopanel
    else
        dark nopanel
    fi
fi



# rules
hc unrule -F
hc set focus_stealing_prevention 1
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole|termite)' focus=on
# hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

hc rule class=Spotify  tag=9



# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc set mouse_recenter_gap 1


# find the panel
panel=~/.config/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

