#!/usr/bin/env bash

# this is a simple config for herbstluftwm

pwd > /tmp/hc-pwd
echo $PATH > /tmp/hc-path



hc() {
    herbstclient "$@"
}

hc emit_hook reload


# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1    # Use left alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-q close
hc keybind $Mod-x close
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-x quit
hc keybind $Mod-Ctrl-Shift-q spawn poweroff
hc keybind $Mod-Ctrl-Shift-x spawn poweroff
hc keybind $Mod-Shift-y reload
hc keybind $Mod-Ctrl-Shift-y spawn reboot
hc keybind $Mod-k spawn xkill
hc keybind $Mod-d spawn termite
hc keybind $Mod-y spawn $HOME/bin/launcher

hc keybind $Mod-Shift-z spawn zsh -i -c movietime # alias from .sh_aliases
hc keybind $Mod-Shift-p spawn zsh -i -c reset-screen # alias from .sh_aliases

# fn+Fxx keys
hc keybind XF86KbdBrightnessDown spawn keyboardbacklightoff
hc keybind XF86KbdBrightnessUp   spawn keyboardbacklightmax
hc keybind XF86MonBrightnessDown spawn /run/wrappers/bin/light -U 5
hc keybind XF86MonBrightnessUp   spawn /run/wrappers/bin/light -A 5
# hc keybind XF86Display spawn
hc keybind XF86TouchpadToggle    spawn touchpadtoggle
hc keybind XF86AudioRaiseVolume  spawn pamixer --increase 5
hc keybind XF86AudioLowerVolume  spawn pamixer --decrease 5
hc keybind XF86AudioMute         spawn pamixer -t

mkdir -p $HOME/screenshots
hc keybind Print                 spawn scrot 'screenshots/%Y-%m-%d_%H-%M-%S_$wx$h.png'           --exec 'notify-send --expire-time=2000 "Fullscreen Screenshot Saved."'
hc keybind $Mod-Print            spawn scrot 'screenshots/%Y-%m-%d_%H-%M-%S_$wx$h.png' --focused --exec 'notify-send --expire-time=2000 "Window screenshot Saved."'
hc keybind $Mod-Ctrl-Print       spawn scrot 'screenshots/%Y-%m-%d_%H-%M-%S_$wx$h.png' --select  --exec 'notify-send --expire-time=2000 "Area Screenshot Saved."'


# adjust volume
hc keybind $Mod-Ctrl-h spawn pamixer --increase 5
hc keybind $Mod-Ctrl-n spawn pamixer --decrease 5
hc keybind $Mod-Ctrl-m spawn pamixer -t

# adjust screen brightness
hc keybind $Mod-Ctrl-g spawn /run/wrappers/bin/light -A 5
hc keybind $Mod-Ctrl-r spawn /run/wrappers/bin/light -U 5
hc keybind $Mod-Ctrl-Shift-g spawn /run/wrappers/bin/light -A 1
hc keybind $Mod-Ctrl-Shift-r spawn /run/wrappers/bin/light -U 1

# switch color scheme
hc keybind $Mod-Ctrl-k spawn $HOME/bin/theme light
hc keybind $Mod-Ctrl-s spawn $HOME/bin/theme dark

# adjust keyboard backlight brightness
hc keybind $Mod-Ctrl-f spawn keyboardbacklightmax
hc keybind $Mod-Ctrl-t spawn keyboardbacklightoff

# lock screen
hc keybind $Mod-esc spawn lock

# control media players with yxcvb (üöäpz on NEO)
hc keybind $Mod-udiaeresis spawn playerctl previous
hc keybind $Mod-odiaeresis spawn playerctl play
hc keybind $Mod-adiaeresis spawn playerctl play-pause
hc keybind $Mod-p          spawn playerctl stop
hc keybind $Mod-z          spawn playerctl next

# enable and disable wifi
hc keybind $Mod-Ctrl-q spawn nmcli radio wifi on
hc keybind $Mod-Ctrl-d spawn nmcli radio wifi off

# set default layout to grid
hc set default_frame_layout 3
hc set_layout grid

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-i     focus left
hc keybind $Mod-a     focus down
hc keybind $Mod-l     focus up
hc keybind $Mod-e     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-i     shift left
hc keybind $Mod-Shift-a     shift down
hc keybind $Mod-Shift-l     shift up
hc keybind $Mod-Shift-e     shift right

# splitting frames
# create an empty frame at the specified direction ( .62 is golden ratio)
hc keybind $Mod-g       chain , split   top    0.38 , focus up
hc keybind $Mod-r       chain , split   bottom 0.62 , focus down
hc keybind $Mod-n       chain , split   left   0.38 , focus left
hc keybind $Mod-t       chain , split   right  0.62 , focus right

# let the current frame explode into subframes
hc keybind $Mod-m split explode
hc keybind $Mod-Shift-m split explode

# resizing frames
resizestep=0.02
hc keybind $Mod-Shift-g         resize up +$resizestep
hc keybind $Mod-Shift-r         resize down +$resizestep
hc keybind $Mod-Shift-n         resize left +$resizestep
hc keybind $Mod-Shift-t         resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index "$i"
        hc keybind "$Mod-Shift-Ctrl-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-c use_index +1 --skip-visible
hc keybind $Mod-Shift-c chain ,  move_index  +1 --skip-visible , use_index +1 --skip-visible
hc keybind $Mod-Shift-Ctrl-c move_index  +1 --skip-visible
hc keybind $Mod-v use_index -1 --skip-visible
hc keybind $Mod-Shift-v chain ,  move_index  -1 --skip-visible , use_index -1 --skip-visible
hc keybind $Mod-Shift-Ctrl-v move_index  -1 --skip-visible

hc keybind $Mod-w use_previous

# layouting
hc keybind $Mod-comma remove
hc keybind $Mod-Shift-comma remove
hc keybind $Mod-Shift-h cycle_layout 1
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-h set_attr clients.focus.floating toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 resize
hc mousebind Mod4-Button1 resize # easier resize for touchpads
hc mousebind $Mod-Button2 zoom # middle click: resize in all directions

# focus
hc keybind $Mod-o   focus_monitor +1
hc keybind $Mod-u   focus_monitor -1

hc keybind $Mod-Shift-o          chain , shift_to_monitor +1 , focus_monitor +1
hc keybind $Mod-Shift-u          chain , shift_to_monitor -1 , focus_monitor -1
hc keybind $Mod-Shift-Ctrl-o     chain , shift_to_monitor +1
hc keybind $Mod-Shift-Ctrl-u     chain , shift_to_monitor -1




hc keybind $Mod-Tab cycle
hc keybind $Mod-b jumpto urgent


hc set focus_crosses_monitor_boundaries true


hc set always_show_frame 0
hc set frame_border_inner_width 0
hc set window_border_inner_width 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_border_inner_width 0
hc set frame_gap 0
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1



# rules
hc unrule -F
hc set focus_stealing_prevention 1
hc rule focus=on # normally focus new clients
#hc rule class=XTerm tag=3 # move all xterms to tag 3
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole|termite)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on focus=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class="Signal"  tag=1
hc rule class="VirtualBox Manager"  tag=6
hc rule class="KeePassXC"  tag=8
hc rule class="Spotify"  tag=9



# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc set auto_detect_monitors true
hc set mouse_recenter_gap 1


$HOME/bin/theme light
nm-applet
