{pkgs, ...}: {
  home.packages = with pkgs; [
      # shell / TUI essentials
      tmux
      zellij
      wget
      curl
      gnugrep
      gnused
      procps
      iproute2
      htop
      atop
      btop
      ncdu
      gdu
      duf
      pv
      bat
      lazygit
      tig
      git-fire
      nvd # diff nix generations/closures (used to verify rebuilds)
      dasel
      jq
      fd
      tldr
      gh
      tmate
      upterm
      entr
      socat
      ripgrep-all
      ouch
      atool
      p7zip
      zip
      unzip
      unrar
      tree
      moreutils
      netcat
      nmap
      calc
      inotify-tools
      lsof
      psmisc
      file
      smem
      dnsutils
      kondo
      yt-dlp
      flyctl
      miniserve
      gnumake
      gnupg
      openssl
      man
      exiftool
      qrencode
      trashy
      neovim-remote # used by nvim theme switcher
      bubblewrap
      nono
      pgcli
      sqlite-interactive
      timewarrior
      speedtest-cli
      nethogs
      devbox # install dev tools in project; zshrc ruft `devbox global shellenv` (shell.nix)
      # neovim editing stack
      clang # cc for nvim treesitter
      tree-sitter
      sccache
      rust-script
      python3
      nodejs
      # language servers / formatters / linters
      nixd
      lua-language-server
      luarocks
      stylua
      lua
      nil
      nixfmt
      statix
      gopls
      gofumpt
      gomodifytags
      impl
      delve
      tailwindcss-language-server
      taplo
      docker-ls
      kotlin
      kotlin-language-server
      ktlint
      ruff
      pyright
      hadolint
      vtsls
      vscode-langservers-extracted
      bash-language-server
      shellcheck
      shfmt
      marksman
      markdownlint-cli2
      rtk
    ];
}
