{ lib, ... }:
let
  mergeAttrs = builtins.foldl' (acc: attrs: acc // attrs) { };

  collectFiles =
    root: skipped:
    let
      walk =
        prefix: dir:
        mergeAttrs (
          lib.mapAttrsToList (
            name: type:
            let
              relPath = if prefix == "" then name else "${prefix}/${name}";
              path = dir + "/${name}";
            in
            if builtins.elem relPath skipped then
              { }
            else if type == "directory" then
              walk relPath path
            else if type == "regular" || type == "symlink" then
              {
                "${relPath}" = {
                  source = path;
                };
              }
            else
              { }
          ) (builtins.readDir dir)
        );
    in
    walk "" root;
in
{
  # Home Manager owns these links so $HOME stays runtime state, not a git worktree.
  xdg.configFile = collectFiles ../../home/config [
    # These paths are generated by dedicated Home Manager modules.
    "alacritty/alacritty.toml"
    "gtk-3.0/settings.ini"
    "user-dirs.dirs"
    "yazi/keymap.toml"
    "yazi/yazi.toml"
  ];
  home.file = collectFiles ../../home/files [
    # GTK is generated from the declarative gtk options.
    ".gtkrc-2.0"
  ];
}
