{
  config,
  lib,
  pkgs,
  mkDevSource,
  ...
}: let
  repoDir = "${config.home.homeDirectory}/projects/dotfiles";
  # nix-Pfad zur Repo-Wurzel (dieses Modul liegt unter modules/home-manager/),
  # um Datei/Verzeichnis-Typ von devLinks-Einträgen rein zu bestimmen.
  repoRoot = ../..;

  # nono agent.json wird generiert: Basis aus der gepflegten Repo-Datei, plus
  # aus my.devLinks abgeleitete read-only Leserechte auf die out-of-store Pfade.
  # Siehe docs/superpowers/specs/2026-06-16-dev-links-design.md.
  agentBase = builtins.fromJSON (builtins.readFile ../../home/config/nono/profiles/agent.json);

  # "directory" -> read (Verzeichnis), sonst read_file (Einzeldatei).
  devLinkIsDir = relPath:
    (builtins.readDir (dirOf (repoRoot + "/${relPath}"))).${baseNameOf relPath} == "directory";
  devLinkAbs = relPath: "${repoDir}/${relPath}";

  devLinkDirs = map devLinkAbs (builtins.filter devLinkIsDir config.my.devLinks);
  devLinkFiles = map devLinkAbs (builtins.filter (p: !devLinkIsDir p) config.my.devLinks);

  agentProfile =
    agentBase
    // {
      filesystem =
        agentBase.filesystem
        // {
          read = agentBase.filesystem.read ++ devLinkDirs;
          read_file = agentBase.filesystem.read_file ++ devLinkFiles;
        };
    };

  agentJson = (pkgs.formats.json {}).generate "nono-agent-profile.json" agentProfile;

  mergeAttrs = builtins.foldl' (acc: attrs: acc // attrs) {};

  collectFiles = repoRelRoot: root: skipped: let
    walk = prefix: dir:
      mergeAttrs (
        lib.mapAttrsToList (
          name: type: let
            relPath =
              if prefix == ""
              then name
              else "${prefix}/${name}";
            path = dir + "/${name}";
          in
            if builtins.elem relPath skipped
            then {}
            else if type == "directory"
            then walk relPath path
            else if type == "regular" || type == "symlink"
            then {
              "${relPath}" = {
                source = mkDevSource "${repoRelRoot}/${relPath}" path;
              };
            }
            else {}
        ) (builtins.readDir dir)
      );
  in
    walk "" root;
in {
  # Home Manager owns these links so $HOME stays runtime state, not a git worktree.
  xdg.configFile =
    (collectFiles "home/config" ../../home/config [
      # These paths are generated by dedicated Home Manager modules.
      "alacritty/alacritty.toml"
      "gtk-3.0/settings.ini"
      "user-dirs.dirs"
      "yazi/keymap.toml"
      "yazi/yazi.toml"
      # nono sandbox profile for AI agents: nix-generiert (unten), nicht kopiert.
      "nono/profiles/agent.json"
    ])
    // {
      "nono/profiles/agent.json".source = agentJson;
    };
  home.file = collectFiles "home/files" ../../home/files [
    # GTK is generated from the declarative gtk options.
    ".gtkrc-2.0"
  ];
}
