[light]
[light.bright]
black = '#999999'
blue = '#77c4ff'
cyan = '#65cabe'
green = '#68af5d'
magenta = '#8468cb'
red = '#ff72bd'
white = '#ffffff'
yellow = '#ffa34a'

[light.normal]
black = '#000000'
blue = '#0a94ff'
cyan = '#00cab2'
green = '#19af00'
magenta = '#3b00cb'
red = '#ff0088'
white = '#ffffff'
yellow = '#ff7e00'

[light.primary]
background = '#ffffff'
foreground = '#000000'

[palenight]
[palenight.bright]
black = '#434758'
blue = '#9cc4ff'
cyan = '#a3f7ff'
green = '#ddffa7'
magenta = '#e1acff'
red = '#ff8b92'
white = '#ffffff'
yellow = '#ffe585'

[palenight.normal]
black = '#292d3e'
blue = '#82aaff'
cyan = '#89ddff'
green = '#c3e88d'
magenta = '#c792ea'
red = '#f07178'
white = '#d0d0d0'
yellow = '#ffcb6b'

[palenight.primary]
background = '#292d3e'
foreground = '#d0d0d0'


# TokyoNight Alacritty Colors
# Default colors
[tokyonightstorm.primary]
background = '#24283b'
foreground = '#c0caf5'

#[tokyonightstorm.cursor]
#cursor = '#c0caf5'
#text = '#24283b'

# Normal colors
[tokyonightstorm.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[tokyonightstorm.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[tokyonightstorm.indexed_colors]]
index = 16
color = '#ff9e64'

[[tokyonightstorm.indexed_colors]]
index = 17
color = '#db4b4b'
