# tokyo night moon

[colors.bright]
black = "#636da6"
blue = "#82aaff"
cyan = "#86e1fc"
green = "#c3e88d"
magenta = "#c099ff"
red = "#ff757f"
white = "#c8d3f5"
yellow = "#ffc777"

[colors.cursor]
cursor = "#c8d3f5"
text = "#222436"

[colors.normal]
black = "#222436"
blue = "#82aaff"
cyan = "#86e1fc"
green = "#c3e88d"
magenta = "#c099ff"
red = "#ff757f"
white = "#c8d3f5"
yellow = "#ffc777"

[colors.primary]
background = "#222436"
bright_foreground = "#c8d3f5"
foreground = "#c8d3f5"

[colors.selection]
background = "#2d3f76"
text = "#c8d3f5"
