#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#000000'

nitrogen --restore

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-y reload
hc keybind $Mod-q close
hc keybind $Mod-k spawn xkill
hc keybind $Mod-d spawn termite
hc keybind $Mod-Shift-p spawn xrandr --output eDP1  --auto --primary --output VGA1 --off

# set default layout to grid
hc set default_frame_layout 3
herbstclient set_layout grid

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-i     focus left
hc keybind $Mod-a     focus down
hc keybind $Mod-l     focus up
hc keybind $Mod-e     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-i     shift left
hc keybind $Mod-Shift-a     shift down
hc keybind $Mod-Shift-l     shift up
hc keybind $Mod-Shift-e     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-g       chain , split   top    0.5 , focus up
hc keybind $Mod-r       chain , split   bottom 0.5 , focus down
hc keybind $Mod-n       chain , split   left   0.5 , focus left
hc keybind $Mod-t       chain , split   right  0.5 , focus right
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.02
hc keybind $Mod-Shift-g         resize up +$resizestep
hc keybind $Mod-Shift-r         resize down +$resizestep
hc keybind $Mod-Shift-n         resize left +$resizestep
hc keybind $Mod-Shift-t         resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index $i
    fi
done

# cycle through tags
hc keybind $Mod-c use_index +1 --skip-visible
hc keybind $Mod-Shift-c chain ,  move_index  +1 --skip-visible , use_index +1
hc keybind $Mod-v use_index -1 --skip-visible
hc keybind $Mod-Shift-v chain ,  move_index  -1 --skip-visible , use_index -1

hc keybind $Mod-x use_previous

# layouting
hc keybind $Mod-comma remove
hc keybind $Mod-Shift-h cycle_layout 1
hc keybind $Mod-h floating toggle
hc keybind $Mod-f fullscreen toggle
#hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
#hc keybind $Mod-c cycle
hc keybind $Mod-b jumpto urgent

# colors
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_bg_normal_color '#121212'
hc set frame_bg_active_color '#37BAFF'
hc set frame_transparent_width 2
hc set frame_border_width 0
hc set frame_border_inner_width 0
hc set frame_gap 0
hc set frame_padding 0
hc set window_border_width 1
hc set window_border_normal_color '#7F7F7F'
hc set window_border_active_color '#37BAFF'
# add overlapping window borders
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

hc rule class=Spotify  tag=9


hc keybind $Mod-y spawn "xboomx"
# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
hc set_monitors 1280x1024+0+0 1280x1024+1280+0
or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

